### ISSUE TITLE
查询传感器的值和电视media_player设置问题

### ISSUE THREAD

**Issue by yingzaigt** [Deschanel/DuerSmartHome#1]
大神，有两个问题咨询。1、查询传感器的值还是不行2、我在gate.php中修改填写电视media_player了，只能开关，不能调节音量呢？请大神指点。gate.php修改如下
array(
					"actions"  =>  array("turnOn", "turnOff","AdjustUpVolume","AdjustDownVolume"),
					"applianceTypes"  => array("MEDIA_PLAYER"),
					"additionalApplianceDetails"  =>  array(),
					"applianceId"  =>  "media_player.lgtv",
					"friendlyDescription" =>  "客厅电视",
					"friendlyName"  =>  "客厅电视",
					"isReachable"  =>  true,
					"manufacturerName"  =>  "LG",
					"modelName"  =>  "客厅电视",
					"version"  =>  "1.0"
				),

**Comment by Deschanel** [comment]
电视音量等在调用hass的api时需要把AdjustUpVolume、AdjustDownVolume改成hass识别的命令，需要你去hass的service里查看一下，因为hass设备繁多，有些类型设备我没有，所以我就没有开发此类型的设备，比如电视音量等，抱歉！！！以后我会写一篇教程让所有人能够自行开发！！！

**Comment by yingzaigt** [comment]
谢谢大神回复，期待您的详细教程。第一个问题，传感器查询的问题，我填入了温度传感器，小度音箱和APP端提醒的语音指令是“让客厅温度查询当前温度”，但是操作不成功。请问大神这是什么问题。

**Comment by Deschanel** [comment]
是一直没有返回结果还是直接说操作错误？可否把你传感器的hass配置贴上来我试试！！

**Comment by yingzaigt** [comment]
直接回复“抱歉操作失败了，手动操作一下吧” 温度传感器配置如下：
array(
					"actions"  =>  array("getTemperatureReading"),
					"applianceTypes"  => array("AIR_MONITOR"),
					"additionalApplianceDetails"  =>  array(),
					"applianceId"  =>  "sensor.temperature_158d00010e0431",
					"friendlyDescription" =>  "环境温度",
					"friendlyName"  =>  "客厅温度",
					"isReachable"  =>  true,
					"manufacturerName"  =>  "mi",
					"modelName"  =>  "环境温度",
					"version"  =>  "1.0"

**Comment by Deschanel** [comment]
我目前正在把项目重构一下，现在查询状态功能还没写，最近真的太忙了

**Comment by yingzaigt** [comment]
谢谢，目前传感器查询可以了。百度智能音箱自身提供的示例语句并不准确，查询的语句应该是“查询XXXX(传感器名）的当前温度或湿度”等就。电视音量调节也搞定了。但是静音和设定音量值还没搞定，因为它的控制命令除了action还有value值要传。我看你重构后的控制语句是带playload可以传value值的。期待你重构尽快完成。也期待与你合作一把，把这个技能上线百度技能商店。

**Comment by Deschanel** [comment]
现在有什么问题嘛？

**Comment by yingzaigt** [comment]
我现在用python正在重写这个技能，先用百度自己的oauth服务器，测试没问题。目前正在编写前端方便用户管理设备，后续自己实现oauth，进而实现多用户支持。后续有问题还得请教您。
