### ISSUE TITLE
授权过程遇到must have type or botName

### ISSUE THREAD

**Issue by zhkufish** [Deschanel/DuerSmartHome#2]
一点授权就提示这个. {"status":1,"msg":"must have type or botName"}, 虽然有这个提示, 但是在模拟测试是可以成功打开开关的. 但是跟小度音响说, 打开卧室灯, 会提示"对不起, 小度没能成功获取你的授权"

**Comment by Deschanel** [comment]
我一直是授权成功啊！
我之前也遇到过这个问题，#exit("SUCCESS! Authorization Code: $code");要注释掉
同时client_id和client_secret 建议先用小度文档上的测试一下，成功后再更换自己的，还有数据库的回调地址要写对！
如果以上确认无误，那就去你的数据库看看授权码和token表中是否有最新的数据，切记是最新的，哪一个没有就到相应的文件中调试！

**Comment by zhkufish** [comment]
@Deschanel 谢谢目前已经解决, 原来是因为code参数里面不知道为什么多了下划线, 写了一句代码把下划线去掉就好了. 具体什么原因产生那个下划线的, 我没有去找
