### ISSUE TITLE
控制HA上的Philips Hue

### ISSUE THREAD

**Issue by yeefanwong** [Deschanel/DuerSmartHome#3]
按大神的教材，成功把小度接入HA，目前控制Philips Hue开关没有问题，但调节亮度和颜色都提示"控制超时"，不知道该怎么查原因，在HA的service中测试用rgb_color，brightness_pct调节色彩和亮度都是成功的。

**Comment by Deschanel** [comment]
@yeefanwong 你的details里增加键值对了吗？因为dueros的颜色和亮度指令与hass不同！

**Comment by yeefanwong** [comment]
@Deschanel 增加了，我的设置如下，不知道应该怎么做debug？

  array(
      "actions"  =>  array("turnOn", "timingTurnOn", "turnOff", "timingTurnOff", "setBrightnessPercentage", "setColor"),
      "applianceTypes"  => array("LIGHT"),
      "additionalApplianceDetails"  =>  array("setBrightnessPercentage" => "brightness_pct", "setColor" => "rgb_color"),
      "applianceId"  =>  "light.hue_color_light_3",
      "friendlyDescription" =>  "Philips Hue",
      "friendlyName"  =>  "客厅灯",
      "isReachable"  =>  true,
      "manufacturerName"  =>  "Philips",
      "modelName"  =>  "Philips Hue",
      "version"  =>  "1.0"
    ),

我是码盲，所以刚刚尝试了一下抓包，想看看从nginx服务器发给hass api的指令对不对，结果发现做灯的开关动作时hass能收到正确的指令，但调亮度和颜色的操作，hass则根本没收到任何东西。

**Comment by Deschanel** [comment]
@yeefanwong 已修改，请试一下是否可以！

**Comment by yeefanwong** [comment]
@Deschanel 谢谢！！测试发现下面两个问题：
1. 设置亮度时，hass没有收到亮度值，
2. 设置颜色时，似乎hsvtorgb转换代码有bug，只有设置红色时hass收到的rgb值是对的，设置其它颜色hass收到的rgb值都是[0, 0, 0], 

![brightness](https://user-images.githubusercontent.com/40956560/44625754-49271080-a943-11e8-84ba-4c556c16594f.png)
![green](https://user-images.githubusercontent.com/40956560/44625755-49bfa700-a943-11e8-8ef9-2910cb407ad9.png)
![red](https://user-images.githubusercontent.com/40956560/44625756-49bfa700-a943-11e8-800e-14ce9a99df5f.png)

**Comment by Deschanel** [comment]
@yeefanwong 
颜色我发现我这里可以！
![1](https://user-images.githubusercontent.com/28536132/44627293-fc9cfe80-a95d-11e8-8639-a1d2de2f8531.png)
图片为用postman对技能网关设备地址模拟dueros发送的数据

![2](https://user-images.githubusercontent.com/28536132/44627296-00c91c00-a95e-11e8-9264-d36b7560f686.png)
图片为监听结果

突然发现dueros文档控制类的首字母发现设备中为小写，控制设备中为大写，这边需要注意大小写相同！
[https://dueros.baidu.com/didp/doc/dueros-bot-platform/dbp-smart-home/protocol/discovery-message_markdown](url)
[https://dueros.baidu.com/didp/doc/dueros-bot-platform/dbp-smart-home/protocol/control-message_markdown](url)
![3](https://user-images.githubusercontent.com/28536132/44627322-6fa67500-a95e-11e8-8a2c-ff1136238d4d.png)

所有的图片中为终端监听端口打印出来的json数据
数据监听的代码我用的这个[https://blog.csdn.net/huliang82/article/details/18322033?utm_source=jiancool](url)
是否是你的缓存的原因？

**Comment by yeefanwong** [comment]
@Deschanel  亮度改为小写s后可以了，颜色还是除了红色，其它颜色全都是[0,0,0]，用你提供的那个监听代码抓到的结果 **_{"rgb_color":[0,0,0],"entity_id":"light.hue_color_light_5"}accept a connect_**，重启后还是不行，不知道和php版本有没有关系，我的php是5.6.36。

update
尝试修改dueros.php，跳过rgb转换
![screen shot 2018-08-26 at 20 08 35](https://user-images.githubusercontent.com/40956560/44628099-66240980-a96c-11e8-9a41-5f01c84c65ab.png)
测试调颜色时监听到json数据是正确的，应该还是转换这部分有bug。
**_{"rgb_color":{"hue":120,"brightness":0.5,"saturation":1},"entity_id":"light.hue_color_light_5"}
{"rgb_color":{"hue":249,"brightness":1,"saturation":1},"entity_id":"light.hue_color_light_5"}
{"rgb_color":{"hue":0,"brightness":1,"saturation":1},"entity_id":"light.hue_color_light_5"}_**

**Comment by Deschanel** [comment]
@yeefanwong 我的php版本是7.0，确实是颜色转换的问题，我公式找错了！

**Comment by Deschanel** [comment]
@yeefanwong 以修改！

**Comment by yeefanwong** [comment]
@Deschanel  测试没问题了，谢谢！
