### ISSUE TITLE
打开 authorize.php  404 

### ISSUE THREAD

**Issue by linkboy2007** [Deschanel/DuerSmartHome#4]
h

**Comment by Deschanel** [comment]
@linkboy2007 你服务器上是不是删除了？或者改了名字？

**Comment by linkboy2007** [comment]
我没有删除和改名。我问了别人，他们说是因为程序错误后,程序抛出了404。并不是nginx返回的404。

**Comment by Deschanel** [comment]
@linkboy2007 你看一下nginx和程序运行日志确定是什么错误。

**Comment by Deschanel** [comment]
你是不是oauth2.0库没下载 @linkboy2007

**Comment by linkboy2007** [comment]
解决了。原因不明。oath 下载了
